name: Pull Request
on:
  pull_request:
    branches:
      - main
permissions:
  contents: read
concurrency: ${{ github.workflow }}-${{ github.ref }}
jobs:
  verify:
    name: Verify
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'
      - uses: actions/cache@v4
        with:
          path: .turbo
          key: ${{ runner.os }}-turbo-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-turbo-
      - run: pnpm install
      - run: pnpm run build
      - run: pnpm run lint
